title: "Tri An Le"
author: ""
description: ""
theme: minima

header_pages:
  - publications.md
  - projects.md
  - cv.md

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/TriAnLe171" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/trianle" }